# Generated by Django 3.2 on 2021-05-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
