# Generated by Django 3.2 on 2021-05-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210511_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grad_year',
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.faculty'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
