# Generated by Django 3.2 on 2021-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210517_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grad_year',
            field=models.PositiveSmallIntegerField(default=2025),
        ),
    ]
